### ISSUE TITLE
Send notification to all users

### ISSUE THREAD

**Issue by cesarureno** [dreamonkey/laravel-onesignal-rest-api#3]
I`m triying send notification to all users ang i get this error

`$response = OneSignal::postNotification([
        "contents"              => ["en" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et iaculis enim. Sed egestas porttitor laoreet."],
        "headings"              => ["en" => "Aliquam consectetur odio sed"],
    ]);`

`Client error: 'POST https://onesignal.com/api/v1/notifications' resulted in a '400 Bad Request' response: {"errors":["You must include which players, segments, or tags you wish to send this notification to."]}`

**Comment by IlCallo** [comment]
That's perfectly normal.
I quote from official documentation:

> The Create Notification method is used when you want your server to programmatically send notifications or emails to a segment or individual users. You may target users in one of three ways using this method: by Segment, by Filter, or by Device. **At least one targeting parameter must be specified.**

[source](https://documentation.onesignal.com/reference)

You cannot send a notification to all users, you must specify some kind of ID collection (players, segments or tags)
